Repository Name: PerchSecurity/kibana
Description: ConnectWise SIEM fork of ES kibana 7x
Product: CW Siem
Business Pillar: Cybersecurity
Business Criticality: High
Product Owner: Sravya Mutnuru
Engineering Lead: Robert Farmer
Team Owner ID: 185
Purpose: Product
Type: API/Microservice
User Access: Platform
CI Type: N/A
Exceptions:
